### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by eltociear**

### CODE REVIEW

**Comment by eltociear** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by eltociear** [comment]
recheck

**Comment by LiXiaYu** [comment]
good

**Review by FrankHB — APPROVED** [review]

**Comment by FrankHB** [comment]
Recover merge status.

**Comment by FrankHB** [comment]
Squashed in commit 0c85412371a60c3ba988cdd6f7f744eb7a710710.

**Comment by FrankHB** [comment]
Squashed in commit b84691c5e98ae78c4db365651074b2e8afb77e65.

**Comment by FrankHB** [comment]
Squashed in commit 2ae15de2003ebb55077f90a8c58f25f1300071b8.

**Pull request merged**
