### PR TITLE
build.sh: Fixed linking error

### PR DESCRIPTION
**Pull request by 435qb**

### CODE REVIEW

**Comment by 435qb** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Review by FrankHB — DISMISSED** [review]
Sorry for the late reply, due to the repository under a massive rebase during recent weaks.

Please resolve the following issues:

1. Rebase the changes on the current `master` branch (which is now considered relatively stable against any further repository rewriting, although still not up-to-date to the state of the internal development branches).
2. Update the copyright year "2022" to "2023".
3. In which configuration you need to add `$YSLib_BaseDir/YFramework/source/YSLib/Core/YConsole.cpp`? What linker errors are shown without this source file? This file is not expected relied on. Although there is the plan to add some terminal features to the interpreter which will eventually require this file, it looks suspicous at this time.

**Comment by FrankHB** [comment]
I see. That's referenced by `$YSLib_BaseDir/YFramework/source/YCLib/Host.cpp` in `EXTRA_OPT` for Windows-specific configurations. (Although the functionality is currently not used, it is needed for static linking.) Would you please move it to `*MSYS* | *MINGW*)` case of `EXTRA_OPT`?

(And one more rebase for the last change on the external dependency update. Sorry for inconvenince.)

**Comment by 435qb** [comment]
ok

**Comment by FrankHB** [comment]
As we have added parallel build support in the script, as well as some other bug fixes involving the list of source files (including removal of `EXTRA_OPT`), this PR is outdated. Still thanks for your contribution.

**Pull request closed without merging**
